name: ProjectKorraLevelSystem
version: ${project.version}
main: me.manu.projectkorralevelsystem.ProjectKorraLevelSystem
api-version: '1.20'
author: "Manu"
depend: [ ProjectKorra ]
description: "A ProjectKorra levelling system plugin"