name: ProjectKorraLevelSystem
version: ${project.version}
main: me.manu.projectkorralevelsystem.ProjectKorraLevelSystem
api-version: 1.16
authors: [ Manu, Finn ]
depend: [ ProjectKorra ]
description: A ProjectKorra levelling system plugin